blank_issues_enabled: false
contact_links:
  - name: DNX Brasil
    url: https://dnxbrasil.com/
    about: At DNXBrasil we help your business build better solutions by upgrading how delivery is done, leaving behind manual processes and embracing an automated, cloud-native way of working.
